language: php

php:
    - 7.0
    - 5.6
    - hhvm

before_install:
    - composer self-update --no-interaction

install:
    - composer install --no-interaction --prefer-source

script:
    - bin/phpunit --coverage-text --testdox
